### ISSUE TITLE
metadata_io.write_metadata is a lossy encoding

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#117]
I am not sure if this is intentional, but I have noticed this pattern several times in the codebase and I'm not sure why (it also happens in `metadata_io.read_metadata`).

```
schema_proto = schema_utils.schema_from_feature_spec(
      metadata.schema.as_feature_spec(), metadata.schema.domains())
```

Converting to feature spec is a lossy transformation, and it loses metadata from the underlying schema proto, such as which features should be available at serving time or not. Why not just write the schema proto that's already in the `DatasetMetadata` object?

For context: I use TFT to transform some labels into derived labels and derived label weights. At training time I want to use the metadata produced from TFT to determine which input "features" I can train with and which I should filter out from training by using the `Schema` environment fields. This doesn't seem possible with the way that TFT handles reading and writing metadata at the moment.

**Comment by KesterTong** [comment]
This is because we are in the process of migrating from a legacy Schema object to the Schema proto.  I am in the process of upgrading to remove the roundtrip through feature spec/domains.

Note that unrelated to the above migration, AnalyzeDataset returns a BeamDatasetMetadata which is a subclass of DatasetMetadata that contains both deferred (PCollection) and non-deferred Schemas.  The deferred schema contains things that cannot be known until the Beam pipeline has run, like vocab sizes.

Any time you call DatasetMetadata.schema (like in metadata_io.write_metadata) you will get the non-deferred Schema.  To write the full schema you use the WriteMetadata PTransform.

**Comment by cyc** [comment]
Ah, OK, I was not aware of the historical context.

Thank you for the note about the deferred schema. I was planning to hack around this issue and not noticing that detail would have tripped me up. Looking forward to the coming changes!

**Comment by gowtham-kp** [comment]
@cyc I'm closing this issue as it has been answered. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
