### ISSUE TITLE
Online learning API

### ISSUE THREAD

**Issue by schmidt-jake** [tensorflow/transform#158]
For systems using online learning, the tensorflow-transform preprocessing graph out to be updated online before the new batch(es) train the network. It would be inefficient to recompute the preprocessing graph from scratch every time. Are there plans to extend the API to do preprocessing graph updates in an online way?

**Comment by rmothukuru** [comment]
@JakeTheWise,
Can you please elaborate about your use case.  Thanks!

**Comment by JakeTheWise** [comment]
I have a trained model I want to serve. But every now and again there will be a trigger to perform online learning to adapt the model to new data. I think this is a common pattern and production-grade libraries ought to handle this. I'm not sure how specific you'd like me to be...

**Comment by zoyahav** [comment]
Sorry, I missed this issue previously.
TFT has a chaching mechanism that sort of acts like "online graph updates", it stores as much information as possible to disk in order to avoid re-reading and computing statistics which have already been computed. I'm not sure if this works for your usecase.

Here is an example of using it: https://github.com/zoyahav/tft_notebooks/blob/main/TFT_Cache_example.ipynb

Note that using TFT directly with cache is a bit involved, the process is easier when using TFX Transform which uses TFT and handles cache for the user.

**Comment by UsharaniPagadala** [comment]
@schmidt-jake 

Closing this issue as it is resolved.Please feel free to reopen if this still persists.Thanks
