### ISSUE TITLE
TypeError: Dimension value must be integer got <tf.Tensor 'max/min_and_max/Placeholder_1:0' while using tft Analyzer inside preprocessing function

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/transform#169]
How can I use a tf.Transform analyzer variable within the preprocessing_fn of my TFX pipeline?

I am using the `tft.max` function to compute the maximum value over the whole dataset, which is defined as an analyzer from looking at the source code. I want to use the result of this analyser in the following function call, but get the following error:

**The transform function**:

```
def preprocessing_fn(inputs):
    outputs = {}
    max_length = tft.max(inputs['MFCC_frame_count'], reduce_instance_dims=True)
    outputs['MFCC_data'] = tft.sparse_tensor_to_dense_with_shape(
        inputs['MFCC_data'],
        [max_length, 26],
        default_value=0
    )
    return outputs
```
**The Error:**
`TypeError: Dimension value must be integer or None or have an __index__ method, got <tf.Tensor 'max/min_and_max/Placeholder_1:0' shape=() dtype=int64>
`
This [Github Issue](https://github.com/tensorflow/tensorflow/issues/27519) looks similar but I couldn't find the solution there. 

Thank you in advance.

**Comment by zoyahav** [comment]
I think you may have to use TF directly to convert the sparse tensor to dense since tft.sparse_tensor_to_dense_with_shape assumes that the input shape is an iterable of primitives (not tensors, which max_length is).
You can use some combination of tf.sparse.reshape and tf.sparse.to_dense.

Note that your current preprocessing_fn doesn't look right to me, as tf.Transform performs a map of the inputs to the outputs, the batch dimension should most likely be the same for tensors in inputs and tensors in outputs (i.e. the first dimension in the output shape should be batch_size, not max_length).

**Comment by rakeshmothukuru1** [comment]
@zoyahav,
Thank you for the clarification.

**Comment by varshaan** [comment]
Some additional context for future reference:

TFT by default still uses TF 1 Graphs and Sessions internally.

Tensors in TF 1 are indicators of deferred computation. Since the preprocessing_fn is traced into a graph, graph tensors have a fixed shape only if every tensor value that will ever be fed for it is the same. 

In the following example for instance, if `inp` was defined as a sparse_placeholder with shape [2,2], we have a  guarantee that no other shape will be fed for it. So we can call `dense.set_shape([2,2])`.

If instead `inp` was a sparse_placeholder with shape [None, None], outp cannot have any shape other than [None, None]. Yes, depending on what value is fed for inp, the shape of outp will change, but that cannot be encoded in the graph tensor.

`set_shape` can have None in its dimensions, so if we have some of the dimensions being static and others being dynamic, we can call `set_shape([None, 2])`. 

This is why the `tft.sparse_tensor_to_dense_with_shape` requires that the shape is static. 

```
def foo(sparse):
 dense = tf.sparse.to_dense(sparse)
 dense.set_shape([None,2])
 return dense

with tf.compat.v1.Graph().as_default() as g:
 inp = tf.compat.v1.sparse_placeholder(tf.int32, shape=[None, 2])
 outp = foo(inp)
 const_t1 = tf.compat.v1.SparseTensorValue(indices=[[1, 0], [1,1]], values=[1, 2], dense_shape=[2,2])
 print(outp) # will have shape [2,2]
 with tf.compat.v1.Session(graph=g) as sess:
   print(sess.run(outp, feed_dict={inp: const_t1})) # np.ndarray
```
