### ISSUE TITLE
Question : How to de-normalize prediction result inside a TFX pipeline?

### ISSUE THREAD

**Issue by ismail-dinar** [tensorflow/transform#179]
I built a TFX pipeline  in which the transform component normalize data using the z-score method and when I make a prediction using the produced model it returns a normalized value.
So my question is: Is there anyway to de-normalize the prediction result inside the pipeline ?

**Comment by zoyahav** [comment]
I'm assuming you're looking for the de-normalization to occur in the prediction stack, is this correct?
This is likely more of a TF question rather than a tf.Transform question, since if you were trying to de-normalize features other than the label post prediction, you would be able to save the pre-transformed value to the preprocessing_fn's output.
This also depends on what you're using for your training.

For example, you could do something similar to what canned estimators do with self._label_vocabulary:
https://github.com/tensorflow/estimator/blob/131f54a62ae9ded9057aeb0eb1243d9516373b14/tensorflow_estimator/python/estimator/head/multi_class_head.py#L289

After prediction they map the predicted categorical integer back to a string value from the vocabulary.
You could similarly reverse the transformation that you're using by saving the constants, for example in the case of z_score mean and variance:
https://github.com/tensorflow/transform/blob/91f18db813e22277306cf2f42e6e09ed7fdf5271/tensorflow_transform/mappers.py#L432-L457
