### ISSUE TITLE
How to apply a pyfunc during analysis phase without saving a pyfunc in the graph?

### ISSUE THREAD

**Issue by cyc** [tensorflow/transform#212]
Here's a situation I encountered recently. Let's say that I want to apply a [box-cox transformation](https://en.wikipedia.org/wiki/Power_transform#Box%E2%80%93Cox_transformation) to my features, but doing so requires estimating a parameter, lambda, using maximum likelihood estimation. Obviously, that might be hard to do directly in TFT, but it is perhaps more feasible to use the [`quantiles`](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/quantiles) analyzer to compute some fixed number of quantiles of the distribution, and then apply an existing scipy library to estimate lambda from the quantiles.

Doing that in TFT might look like this:

```python
from scipy import stats

def estimate_lambda(x):
    return np.array([stats.boxcox_normmax(x, method='mle')], np.float32)

quantiles = tft.quantiles(feature, num_buckets=100, epsilon=0.01)
lamb = tft.apply_pyfunc(estimate_lambda, tf.float32, False, 'estimate_lambda', quantiles)
lamb.set_shape([1])
# Then use TF ops to transform `feature` via box-cox with parameter `lamb`.
```

This works great for transforming the data, but unfortunately doesn't work when serializing the resulting graph for serving due to the pyfunc being baked into it.

Is there a way to do this (use a third-party pyfunc such as a scipy function during the analysis phase) without using `tft.apply_pyfunc`? The only thing I can think of is to write my own custom combiner.

**Comment by zoyahav** [comment]
Yes, I believe currently the only way is to avoid using pyfunc since that by definition adds it to the graph, we still need to apply the function in a deferred manner since the output of quantiles is deferred, so as you said we'd have to put it as part of the analysis beam graph with a custom *analyzer*.
Here's an example using [`tft.ptransform_analyzer`:
](https://www.tensorflow.org/tfx/transform/api_docs/python/tft/ptransform_analyzer)

```python
import apache_beam as beam

def numpy_fn(inputs):
  input, = inputs
  return np.prod(input)

class NumpyPTransform(beam.PTransform):
  def expand(self, pcoll):
    result = (
        pcoll 
        | 'ExtractOne' >> beam.combiners.Sample.FixedSizeGlobally(1)
        | 'FlattenSingleInput' >> beam.FlatMap(lambda x: x) 
        | 'RunNumpyFn' >> beam.Map(numpy_fn))
    return (result,)

def preprocessing_fn(inputs):
    """Preprocess input columns into transformed columns."""
    x = inputs['x']
    y = inputs['y']

    num_quantiles = 5
    q = tft.quantiles(x, num_quantiles, epsilon=0.01)
    outputs = tft.ptransform_analyzer(
         inputs=[q],
         output_dtypes=[tf.float32],
         output_shapes=[[num_quantiles]],
         ptransform=NumpyPTransform())

    return {
        'x': tf.zeros_like(x) + outputs[0],
        'y': y,
    }
```

This will likely be significantly less efficient than using pyfunc.
There could possibly be a way to annotate a resulting tensor of a pyfunc call as a constant which would not prevent it from being serialized with the graph, but may disconnect it from the execusion path for transformation, but that's not possible today and would require a bit more thought on our end.

**Comment by cyc** [comment]
@zoyahav thank you for the suggestion (I was not aware of `tft.ptransform_analyzer`) and for the code example, I will give this a try. Would you like me to close this ticket out once I do?

**Comment by zoyahav** [comment]
No problem, yes please do let us know if you run into any issues with this, and close this issue otherwise.

**Comment by cyc** [comment]
@zoyahav It worked perfectly, thank you! 

>There could possibly be a way to annotate a resulting tensor of a pyfunc call as a constant which would not prevent it from being serialized with the graph, but may disconnect it from the execusion path for transformation, but that's not possible today and would require a bit more thought on our end.

IMO, if `tft.apply_pyfunc(stateful=False)` is used, it should imply that the op can be resolved as a deterministic function of its inputs. So if in the graph we have a constant as input to the pyfunc, then it can just be replaced with a constant as the output for the purposes of transformation.

Not sure if it's worth the hassle of implementing, but it would make using pyfuncs during TFT substantially more useful.

**Comment by zoyahav** [comment]
Note that the issue here is not that the op is a deterministic function of its inputs, but instead that its inputs are unknown at this time (they are dependants of placeholders).
The issue is that since pyfuncs are used as is in the TF graph, anywhere where this graph is run has to have a python environment. If instead pyfuncs were somehow converted to a TF graph then that could work.
What I suggested was that if the inputs can be determined during analysis then we can run the function once the inputs are known and store the result as a constant in the graph. We would need to analyze and see how common/useful it is to allow pyfuncs on "constant" inputs.

**Comment by cyc** [comment]
Got it, thanks for clarifying.
