### ISSUE TITLE
how could it combine the transform_fn graph and main model graph when I use the session.run style code？

### ISSUE THREAD

**Issue by xexiyong** [tensorflow/transform#233]
As the title means, last year I develop the DL model in tf 1.0,  and now the preprocess should use the tf-transform instead of python function. when it comes to the save model procedure,  I found the example code in this repo are all made of keras or estimator component, it seems no way if I using session.run.  is that supported using session.run style code?

**Comment by xexiyong** [comment]
the current model is sorts of many customized layers and building blocks... just I wanna modify less code to do it

**Comment by zoyahav** [comment]
This can be done with session.run style code as well.
When using TF sessions we have to keep the current TF graph in mind, it's either implicit or explicit.
Regardless, the following will add the preprocessing logic to the current TF graph:
```
tft_output = tft.TFTransformOutput(path_to_tft_output)
tft_output.transform_raw_features(features, drop_unused_features=True)
```

Note that here features is a dict of str names to graph Tensors.
See example here, where you can see that the graph definition changes due to the loading of the tf.transform graph:
https://github.com/zoyahav/tft_notebooks/blob/main/TFT_output_with_tf_Graph.ipynb

**Comment by arghyaganguly** [comment]
Closing this as it has been awaiting response for quite some time.Please feel free to reopen with questions/insights following the above comment trace.Thanks.
