### ISSUE TITLE
Unit testing TFT functions

### ISSUE THREAD

**Issue by Eng2019git** [tensorflow/transform#235]
Hi all,
I want to do unit test on my functions that contains Tensorflow Transform operations. Something like this:

```
@pytest.mark.parametrize("inputs,expected_result",
    [(
        tf.linspace(start=0, stop=10, num=10),
        tf.linspace(start=0, stop=1, num=10),
    )]
)
def test_tft_scale(inputs, expected_result):
    out = tft.scale_to_0_1(inputs)
    assert tf.experimental.numpy.allclose(out, expected_result)
```

I got error related to eager execution:
```RuntimeError: tf.placeholder() is not compatible with eager execution```

I tried disabling eager execution by putting ```tf.compat.v1.disable_eager_execution()``` , the operation can be performed without error, but then because eager execution is disabled, after performing ```tft``` operation, ```out == <tf.Tensor 'scale_to_0_1/add_1:0' shape=(10,) dtype=float32>``` while ```expected_result == <tf.Tensor 'expected_result:0' shape=(10,) dtype=float64>``` and I can't get evaluate the value of those tensors to compare using ```assert```.

How to solve this? Thanks!

**Comment by arghyaganguly** [comment]
@Eng2019git , please try with [assertAllClose](https://www.tensorflow.org/api_docs/python/tf/test/TestCase#assertAllClose) and design your unit test using [TestCase.](https://www.tensorflow.org/api_docs/python/tf/test/TestCase)

**Comment by zoyahav** [comment]
tf.transform mappers which rely on analysis such as `tft.scale_to_0_1` must be invoked in a preprocessing_fn within a Beam graph, it can't be called directly like is done in your example.
The placeholder error you're observing is because `tft.scale_to_0_1` is defining deferred computation which will be accumulated over all of the inputs in your dataset, those inputs will be fed to this placeholder.

You could use tft_unit to unittest your preprocessing_logic, more specifically `tft_unit.assertAnalyzeAndTransformResults` see an example here:
https://github.com/tensorflow/transform/blob/018e0e809ad2353b9ae4c537692f5f81de91fc94/tensorflow_transform/beam/impl_test.py#L376-L406

**Comment by arghyaganguly** [comment]
Closing this as it has been awaiting response for some time.Please feel free to reopen based on the comment trace above.Thanks.
