### ISSUE TITLE
Apply TFIDF on Text Data Using TFX Transform Component

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/transform#241]
Hi,

I was trying to build end to end pipeline for Text Classification Problem using TFX Components. I was able to load Text data to CSV ExampleGen Component and completed with Schema and StatisticsGen Components.

So As part of next pipeline, I would like to Transform Text data to TFIDF Vectors also use NLTK library for removing stopwords and apply Lemmatizer and tokenize and Build Keras Model using Trainer Component.

But I couldn't find proper documentation for above process and found difficulty in applying TFX Components for text classification. So please guide me with above process and provide necessary steps.

Thanks.

**Comment by zoyahav** [comment]
Could you expand on what you've tried and the issues you've run into?
For TFIDF we have this example: https://www.tensorflow.org/tfx/transform/api_docs/python/tft/tfidf#example_usage
Regarding using NLTK library, I don't believe that's available as TF ops whilch is required in order to use it in TFX Transform, perhaps there are alternatives such as tf.text?

Perhaps this blog post would also be of interest: https://blog.tensorflow.org/2020/06/part-2-fast-scalable-and-accurate-nlp.html

**Comment by arghyaganguly** [comment]
@cah-aswini-jalla , closing this as there has been no update on this thread for sometime.Please feel free to reopen based on the comment by @zoyahav.Thanks.
