### ISSUE TITLE
Transform without having to write to disk

### ISSUE THREAD

**Issue by galderic** [tensorflow/transform#49]
Is it possible to transform features on the fly while feeding the training input pipeline? In a similar way as the 'normalizer_fn' works in tf.feature_column.numeric_column.  In all the examples I've seen everything is transformed, written to disk, and then read back. I'd like to be able to use (or wrap) the PCollection as a tf.data.DataSet.

**Comment by KesterTong** [comment]
What you have above is almost enough to do the trainer code (given @zoyahav's answer above for the transform code).  The only thing missing is that you need to create an iterator as tf.Transform doesn't directly integrate with tf.Dataset.  e.g.

```
raw_features = dataset.make_one_shot_iterator().get_next()
_, transformed_features = saved_transform_io.partially_apply_saved_transform(
    ...path to output of tf.Transform...,
    raw_features)

transformed_labels = transformed_features.pop(...key of transformed label...)

return transformed_features, transformed_labels
```

**Comment by galderic** [comment]
Thanks @zoyahav and @KesterTong . I finally manage to make it work. 

If you think a complete example using csv, datasets and tf-transform might be useful just say so and I'd submit a pull request with it.

thanks

**Comment by KesterTong** [comment]
Yes that would be great, we'd be happy to review a PR.  We can discuss in a PR but the example should be based on a publicly downloadable dataset like the existing ones are.  https://archive.ics.uci.edu/ml/datasets.html is a good source of sample datasets.  Also please follow the structure of census_example.py as closely as possible, although it will be slightly different due to not materializing the data.  Looking forward to seeing your work.
