### ISSUE TITLE
Normalize subgroups

### ISSUE THREAD

**Issue by The-Fonz** [tensorflow/transform#56]
Hi,

What I'd like to be able to do is normalize a column per subgroup, so per key that is contained in another column. Something like `.groupby('column').apply(normalizefunc)` in pandas, and I guess I can implement it in Beam using `GroupByKey` but the prospect of having an automatically generated transform graph for use during inference is just very attractive.

I looked through the source and can't find this functionality but it looks like you guys are doing similar things with tf-idf and similar computations. Did I overlook this groupby-scale functionality, is it in the works or something you envision implementing in the near future?

**Comment by KesterTong** [comment]
We are working on group-by-key based analyzers.   Do you have a specific use case in mind?  tf-idf is not implemented with a group-by-key approach, so you could potentially copy its implementation for your own use case.  Generally we would expected group-by-key based analyzers to be faster but they may not have any advantage when the data being aggregated is small, as would typically be the case for a numeric analyzer.

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
